default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: fungiorbis
  password: fungiorbis

development:
  <<: *default
  host: localhost
  database: fungiorbis_development
#  socket: /var/run/mysqld/mysqld.sock

test: &test
  <<: *default
  host: localhost
  database: fungiorbis_test

production:
#  <<: *default
  adapter: mysql2
  encoding: utf8
  socket: /var/run/mysqld/mysqld.sock
  url: <%= ENV['database_url'] %>

cucumber:
  <<: *test